FROM node:13.12.0-alpine AS build-env

WORKDIR /modules

COPY package.json .
RUN npm install


FROM gcr.io/distroless/nodejs 

COPY --from=build-env /modules/ /app/
COPY /code/ /app/

EXPOSE 3000
WORKDIR /app/bin

CMD [ "www" ]

