FROM node:13.12.0-alpine AS build-env

WORKDIR /modules

COPY package.json .
RUN npm install


FROM node:13.12.0-alpine 

COPY --from=build-env /modules/ /app/
COPY /code/ /app/

EXPOSE 3000
WORKDIR /app

CMD [ "npm", "start" ]

